baseURL = '/'  # This will be overridden by --baseURL flag
languageCode = 'en-us'
title = 'Reva'
theme = 'hermit-v2'

copyright = "Reva"
enableEmoji = true

[build]
  writeStats = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[params.author]
  name = "Reva"
  # about = "We will help you build a solid foundation for your business to use AI not for the sake of it, but in a way that works for your business and your customers."

[params]
  # New Meta and Social Media Parameters
  description = "Many businesses invest in AI without seeing real returns. Reva helps you use the latest and greatest advancements to help your business get the best outcomes for your tasks."
  # images = ["/images/default-social.jpg"]
  twitter = "@TryRevaAI"
  
  # Existing Parameters
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#1E201F"
  footerCopyright = "Reva"
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = false
  # readTimeSeparator = "CHANGE ME READ TIME"
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # descriptionInPosts= true
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]

  [services]
  [services.googleAnalytics]
  id = 'G-NG5MGX906W'

  # New parameters for environment handling
  production = false  # This will be true for production builds
  
[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  # [[menu.main]]
  #   name = "About"
  #   url = "about-hugo/"
  #   weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # This allows HTML in markdown

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^VERCEL_']  # Allow Hugo to access these environment variables