name: Deploy Hugo PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages-pr-${{ github.event.pull_request.number }}"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      
      # Add Node.js setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './components/package-lock.json'

      # Install and build React components
      - name: Install Components dependencies
        working-directory: ./components
        run: npm ci
      
      - name: Build React components
        working-directory: ./components
        run: npm run build

      # Continue with Hugo build
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      
      # Create PR preview directory
      - name: Create PR preview directory
        run: mkdir -p "public/pr-preview/pr-${{ github.event.pull_request.number }}"
      
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: preview
          TZ: America/Los_Angeles
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "https://blog.tryreva.com/pr-preview/pr-${{ github.event.pull_request.number }}/" \
            -d "public/pr-preview/pr-${{ github.event.pull_request.number }}"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          name: "pr-preview-${{ github.event.pull_request.number }}"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "pr-preview-${{ github.event.pull_request.number }}"
          preview: true

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const url = `https://blog.tryreva.com/pr-preview/pr-${{ github.event.pull_request.number }}/`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `📝 Preview this PR at: ${url}`
            });